
[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

[cursor]
style = "Block"

[font]
size = 17.0

[font.normal]
family = "Iosevka Nerd Font"

[font.bold]
family = "Iosevka Nerd Font"

[font.bold_italic]
family = "Iosevka Nerd Font"

[font.italic]
family = "Iosevka Nerd Font"

[window]
startup_mode = "Maximized"
dynamic_padding = true
opacity = 0.86
padding.x = 1
padding.y = 1
decorations = "Buttonless"

[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[terminal]
