# import = ["~/.config/alacritty/catppuccin-macchiato.toml"]
import = ["~/.config/alacritty/rose-pine.toml"]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

[cursor]
style = "Block"

[font]
size = 15.0

[font.normal]
family = "MesloLGS Nerd Font"

[font.bold]
family = "MesloLGS Nerd Font"

[font.bold_italic]
family = "MesloLGS Nerd Font"

[font.italic]
family = "MesloLGS Nerd Font"

[window]
startup_mode = "Maximized"
dynamic_padding = true
opacity = 1
padding.x = 1
padding.y = 1
decorations = "Buttonless"
